### ISSUE TITLE
AMOLED vs LCD

### ISSUE THREAD

**Issue by vbrh-immalle** [MathiasV-immalle/StageVerslag#1]
Motiveer mogelijk subjectieve meningen zoals "AMOLED is beter dan LCD".

**Comment by MathiasV-immalle** [comment]
Deze info heb ik expres niet vermeld, net omdat het subjectief was. Deze info heb ik wel voorzien op mijn GIP-site. Ik zal deze info nu ook bijvoegen in de 'README.md'.

**Comment by MathiasV-immalle** [comment]
info toegevoegd.
